#!/bin/bash

machine=${1:-0}
model=${2:-controller}
ip=`juju machines -m controller --format=json | jq '.machines[]."dns-name"'`

echo machine $machine

read -d '' -r cmds <<'EOF'
conf=/var/lib/juju/agents/machine-*/agent.conf
user=`sudo grep tag $conf | cut -d' ' -f2`
echo user: $user
password=`sudo grep statepassword $conf | cut -d' ' -f2`
echo pass: $password
echo ""
PATH="$PATH:$(echo /usr/lib/juju/mongo*/bin)"
mongo 127.0.0.1:37017/juju --authenticationDatabase admin --ssl --sslAllowInvalidCertificates --username "$user" --password "$password"
EOF

echo ip $ip

juju ssh -v -m $model $machine "$cmds"
